# NumPy
NumPy is the core library for scientific computing in Python. Foundational Python Libraries such as 'pandas', 'SciPy' and 'Matplotlib' are built on top of NumPy's API. Even Machine learning libraries such as 'TensorFlow' and 'scikit-learn' uses 'NumPy' arrays as inputs.

## General
### Why uses 'arrays' instead of 'lists'
- 'list' can contain different data types. But 'array' needs to have elements of same datatype. Which makes 'numpy' efficient because it doesn't need to check the datatype of each element. Also takes up less space and memory.

# Numpy Arrays

'array' is the main object in numpy. An array can have any number of dimensions and each dimension can be any length.

## Creating Arrays

In [ ]:
import numpy as np

# Create one dimensional array
arr = np.array([1, 2, 3, 4, 5])
print("One dimentional Array:", arr)

# Create 2 dimensional array
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print("Two dimensional Array:", arr)

# Create arrays using 'numpy' methods
# From np.zeros
arr = np.zeros((5,3))
print("Zeros Array:", arr)

# From np.random.random
arr = np.random.random((2,4))
print("Random Array:", arr)

# From np.arange()
arr = np.arange(-3,4) # Starts from first parameter to second parameter - 1. Step of 1.
print("Arange Array default:", arr)

arr = np.arange(4) # Starts from 0 to 'n-1'
print("Arange Array one parameter:", arr)

arr = np.arange(-3,4,3) # Step of 3
print("Arange Array with step:", arr)

# 3D Arrays
array_1_2D = np.array([
    [1,2],
    [3,4]
])
array_2_2D = np.array([
    [5,6],
    [7,8]
])
array_3_2D = np.array([
    [9,10],
    [11,12]
])

array_3D = np.array([array_1_2D, array_2_2D, array_3_2D])
print("Array 3D:", array_3D)


One dimentional Array: [1 2 3 4 5]
Two dimensional Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Zeros Array: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Random Array: [[0.43777783 0.38138946 0.8864704  0.41069906]
 [0.3466576  0.58364717 0.12761061 0.79054729]]
Arange Array default: [-3 -2 -1  0  1  2  3]
Arange Array one parameter: [0 1 2 3]
Arange Array with step: [-3  0  3]


# Array Types
- Array Types are 'vectors'(one dimensional), 'matrix'(two dimensional), 'tensor'(three or more dimensional)

## Vector Arrays
- 'vector' array is an 'array' with one dimension.
- There is no difference between 'row' or 'column'. 'Horizontal' one dimensional vector is equal to 'Vertical' one dimensional vector.
- How is this useful. Vector embedding: a NumPy vector that represents meaning 

In [ ]:
vector = np.array([1, 2, 3, 4])
vector.shape  # (4,) - one dimension with 4 elements
vector.ndim   # 1

## Matrix
- Are 2 dimensional arrays

In [8]:
matrix = np.array([[1, 2, 3, 4]]) # 2 dimensional(1,4)
print("2 Dimensional Matrix 1 row 4 elements")
print(matrix.shape) # (1,4) - one row with 4 elements
print(matrix.ndim)

matrix = np.array([
        [1], 
        [2], 
        [3], 
        [4]
]) # 2 dimensional(4,1)
print("2 Dimensional Matrix 4 rows 1 element")
print(matrix.shape) # (4,1) - Four row with 1 element
print(matrix.ndim)

2 Dimensional Matrix 1 row 4 elements
(1, 4)
2
2 Dimensional Matrix 4 rows 1 element
(4, 1)
2


## Tensors
- Arrays with 3 or more dimensions

In [9]:
array_1_2D = np.array([
    [1,2],
    [3,4]
])
array_2_2D = np.array([
    [5,6],
    [7,8]
])
array_3_2D = np.array([
    [9,10],
    [11,12]
])

array_3D = np.array([array_1_2D, array_2_2D, array_3_2D])
print("Array 3D:", array_3D)

Array 3D: [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


# Array Attributes & Methods

## Attributes
- `shape`

In [ ]:
arr = np.array([1,2,3,4])
print(arr.shape) # 1D array

arr = np.array([
    [1,2,3,4],
    [5,6,7,8]])
print(arr.shape) # 2D Array

(4,)
(2, 4)


## Methods
- `.flatten()`
- `.reshape()`

In [14]:
# Flatten
arr = np.array([
    [1,2,3,4],
    [5,6,7,8]])
print(arr.flatten())

# Reshape
arr = np.array([
    [1,2,3,4],
    [5,6,7,8]])
print(arr.reshape(4,2))

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Axis
- Axis is an important concept in 'Numpy'.
- '0'(First Dimension) --> Go down the columns. Collapse rows.
- '1'(Second Dimension) --> Go across the 'row'.  Collapse columns

In [ ]:
x = np.array([[1, 2], [3, 4]])

x.sum(axis=0)  # [4, 6] - vertical sum
x.sum(axis=1)  # [3, 7] - horizontal sum

# Data Types
```
np.int32 :- 
np.int64 :- 
np.float32 :- 
np.float64 :- 
```

In [16]:
# Find datatype
np.array([1,2,3,4]).dtype

# Declare datatype as an argument
arr = np.array([1,2,3,4], dtype = np.float32)

# Type Conversion
arr = np.array(
    [
        [True, False],
        [False, False]
    ],
    dtype = np.bool_
)
arr.astype(np.int32)

# Type coercion. Changes the datatype to biggest. In this case 'float64'
np.array([0, 1, 0.001]).dtype
# Having a string, converts all datatypes to 'string'
np.array(['a', 1, 1.34])

array(['a', '1', '1.34'], dtype='<U32')