# NumPy
NumPy is the core library for scientific computing in Python. Foundational Python Libraries such as 'pandas', 'SciPy' and 'Matplotlib' are built on top of NumPy's API. Even Machine learning libraries such as 'TensorFlow' and 'scikit-learn' uses 'NumPy' arrays as inputs.

## General
### Why uses 'arrays' instead of 'lists'
- 'list' can contain different data types. But 'array' needs to have elements of same datatype. Which makes 'numpy' efficient because it doesn't need to check the datatype of each element. Also takes up less space and memory.

# Numpy Arrays

'array' is the main object in numpy. An array can have any number of dimensions and each dimension can be any length.

## Creating Arrays

In [ ]:
import numpy as np

# Create one dimensional array
arr = np.array([1, 2, 3, 4, 5])
print("One dimentional Array:", arr)

# Create 2 dimensional array
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print("Two dimensional Array:", arr)

# Create arrays using 'numpy' methods
# From np.zeros
arr = np.zeros((5,3))
print("Zeros Array:", arr)

# From np.random.random
arr = np.random.random((2,4))
print("Random Array:", arr)

# From np.arange()
arr = np.arange(-3,4) # Starts from first parameter to second parameter - 1. Step of 1.
print("Arange Array default:", arr)

arr = np.arange(4) # Starts from 0 to 'n-1'
print("Arange Array one parameter:", arr)

arr = np.arange(-3,4,3) # Step of 3
print("Arange Array with step:", arr)

# 3D Arrays
array_1_2D = np.array([
    [1,2],
    [3,4]
])
array_2_2D = np.array([
    [5,6],
    [7,8]
])
array_3_2D = np.array([
    [9,10],
    [11,12]
])

array_3D = np.array([array_1_2D, array_2_2D, array_3_2D])
print("Array 3D:", array_3D)


One dimentional Array: [1 2 3 4 5]
Two dimensional Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Zeros Array: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Random Array: [[0.43777783 0.38138946 0.8864704  0.41069906]
 [0.3466576  0.58364717 0.12761061 0.79054729]]
Arange Array default: [-3 -2 -1  0  1  2  3]
Arange Array one parameter: [0 1 2 3]
Arange Array with step: [-3  0  3]


# Array Types
- Array Types are 'vectors'(one dimensional), 'matrix'(two dimensional), 'tensor'(three or more dimensional)

## Vector Arrays
- 'vector' array is an 'array' with one dimension.
- There is no difference between 'row' or 'column'. 'Horizontal' one dimensional vector is equal to 'Vertical' one dimensional vector.
- How is this useful. Vector embedding: a NumPy vector that represents meaning 

In [ ]:
vector = np.array([1, 2, 3, 4])
vector.shape  # (4,) - one dimension with 4 elements
vector.ndim   # 1

## Matrix
- Are 2 dimensional arrays

In [8]:
matrix = np.array([[1, 2, 3, 4]]) # 2 dimensional(1,4)
print("2 Dimensional Matrix 1 row 4 elements")
print(matrix.shape) # (1,4) - one row with 4 elements
print(matrix.ndim)

matrix = np.array([
        [1], 
        [2], 
        [3], 
        [4]
]) # 2 dimensional(4,1)
print("2 Dimensional Matrix 4 rows 1 element")
print(matrix.shape) # (4,1) - Four row with 1 element
print(matrix.ndim)

2 Dimensional Matrix 1 row 4 elements
(1, 4)
2
2 Dimensional Matrix 4 rows 1 element
(4, 1)
2


## Tensors
- Arrays with 3 or more dimensions

In [9]:
array_1_2D = np.array([
    [1,2],
    [3,4]
])
array_2_2D = np.array([
    [5,6],
    [7,8]
])
array_3_2D = np.array([
    [9,10],
    [11,12]
])

array_3D = np.array([array_1_2D, array_2_2D, array_3_2D])
print("Array 3D:", array_3D)

Array 3D: [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


# Array Attributes & Methods

## Attributes
- `shape`

In [ ]:
arr = np.array([1,2,3,4])
print(arr.shape) # 1D array

arr = np.array([
    [1,2,3,4],
    [5,6,7,8]])
print(arr.shape) # 2D Array

(4,)
(2, 4)


## Methods
- `.flatten()`
- `.reshape()`

In [14]:
# Flatten
arr = np.array([
    [1,2,3,4],
    [5,6,7,8]])
print(arr.flatten())

# Reshape
arr = np.array([
    [1,2,3,4],
    [5,6,7,8]])
print(arr.reshape(4,2))

[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


# Axis
- Axis is an important concept in 'Numpy'.
- '0'(First Dimension) --> Go down the columns. Collapse rows. Remember tip '='(Draw 3 lines and they look like zero)
- '1'(Second Dimension) --> Go across the 'row'.  Collapse columns. Remember tip (Columns look like 1)

In [ ]:
x = np.array([[1, 2], [3, 4]])

x.sum(axis=0)  # [4, 6] - vertical sum
x.sum(axis=1)  # [3, 7] - horizontal sum

# Data Types
```
np.int32 :- 
np.int64 :- 
np.float32 :- 
np.float64 :- 
```

In [16]:
# Find datatype
np.array([1,2,3,4]).dtype

# Declare datatype as an argument
arr = np.array([1,2,3,4], dtype = np.float32)

# Type Conversion
arr = np.array(
    [
        [True, False],
        [False, False]
    ],
    dtype = np.bool_
)
arr.astype(np.int32)

# Type coercion. Changes the datatype to biggest. In this case 'float64'
np.array([0, 1, 0.001]).dtype
# Having a string, converts all datatypes to 'string'
np.array(['a', 1, 1.34])

array(['a', '1', '1.34'], dtype='<U32')

# Indexing and Slicing

In [37]:
# Indexing 1D array
arr = np.array([1,2,3,4,5,6])
arr[3] # display 4th element in the array

# Indexing 2D array
arr = np.array([
    [1,2,3,4],
    [4,5,6,7],
    [8,9,10,12]
])
arr[1,2] # arr[row, col]

# Just display row, all columns
arr[0] # Display row 0 with all columns

# Just display column, all rows
arr[:, 0] # Display column 0 with all rows

# Slicing 1D array
arr = np.array([1,2,3,4,5])
arr[2:4] # Displays [3,4].

# Slicing 2D Array
arr = np.array([
    [1,2,3,4],
    [4,5,6,7],
    [8,9,10,12]
])
arr[1:3,2:4] # array([[ 6,  7],[10, 12]])

# Slicing with Steps
arr = np.array([
    [1,2,3,4],
    [4,5,6,7],
    [8,9,10,12],
    [13,14,15,16]
])
arr[1:3:2,2:4:2]


array([[6]])

# Sort

In [40]:
arr = np.array([
    [0,9,11,5],
    [1,18,10,6],
    [22,15,17,4],
    [8,19,14,23]
]
)

np.sort(arr) # By default sorted on 'axis=1' or columns. So each row is taken and sorted from left to right increasing on columns.
np.sort(arr, axis=0) # Sorted based on row. So first column is taken and then it sorted based value in each row from lower to higher.

array([[ 0,  9, 10,  4],
       [ 1, 15, 11,  5],
       [ 8, 18, 14,  6],
       [22, 19, 17, 23]])

# Filtering Arrays
Two ways to filter
- Masks
- np.where

In [51]:
# Filter using mask
arr = np.arange(1,20)
odd_mask = arr % 2 != 0
print(odd_mask) # It will be an array 'True', 'False'. Where 'odd' number has value 'True'.
print(arr[odd_mask]) # Prints out only 'odd' numbers [ 1  3  5  7  9 11 13 15 17 19].

# Filter 2D Array
cars_prices =np.array(
    [
        [1, 20000],
        [2, 30000],
        [3, 40000],
        [4, 50000],
        [6, 60000]

    ]
) # cars and their price.

# Get all cars whose price is less than or equal to 30000
cars_cheaper_than_30k = cars_prices[:, 1] <= 30000
print(cars_cheaper_than_30k) # [ True  True False False False]
print(cars_prices[cars_cheaper_than_30k]) # [[    1 20000][    2 30000]]
print(cars_prices[:,0][cars_cheaper_than_30k]) # Display only car numbers who value is less than or equal to 30000


# np.where() # Returns array of indices which meet the condition
np.where(cars_cheaper_than_30k) # Returns tuple.

# np.where() returns tuples of indices
arr = np.array([
    [0,5,0],
    [0,6,0],
    [0,7,0]
])

row_ind, col_ind = np.where(arr == 0)
print(row_ind)
print(col_ind)

# Find and replace
np.where(arr == 0, -99, arr) # Replaces 0 with -99

[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True]
[ 1  3  5  7  9 11 13 15 17 19]
[ True  True False False False]
[[    1 20000]
 [    2 30000]]
[1 2]
[0 0 1 1 2 2]
[0 2 0 2 0 2]


array([[-99,   5, -99],
       [-99,   6, -99],
       [-99,   7, -99]])

# Adding and Removing Data
np.concatenate :- by default concanetes with 'first' axis(axis=0 or rows). If we need to concatenate along columns we need to pass parameter 'axis=1'. Also make sure 'dimensions' match especially for 1D array.
np.delete :- delete data in array. np.delete(arr, <what to delete>, axis)

In [ ]:
# Row concatenate. Default axis=0
arr_1 = np.array([
    [1,2],
    [3,4],
    [5,6],
    [7,8]
])
arr_2 = np.array([
        [9,10]
])
np.concatenate((arr_1, arr_2))

# Column Concatenate. 'axis' must be 1
arr_1 = np.array([
    [1,2,3],
    [4,5,6]
])
arr_2 = np.array([
    [7,8,9,10],
    [11,12,13,14]
])
np.concatenate((arr_1, arr_2), axis = 1)

# Issue with dimension
arr_1 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(f"Arr 1 Dim : {arr_1.ndim}")
arr_2 = np.array([1,2,3])
print(f"Arr 2 Dim : {arr_2.ndim}")

# If we try to concatenete 2D with 1D we will get error
# np.concatenate((arr_1, arr_2))

# Convert 1 D to 2D
arr_2 = arr_2.reshape((3,1))
np.concatenate((arr_1, arr_2), axis=1)

# Delete. 
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

# Delete row. Axis is 0
np.delete(arr, 1, axis=0)

# Delete col. Axis is 1
np.delete(arr, 1, axis=1)

# No axis provided. Flattens the array and delete the element in flatten array.
np.delete(arr, 1) #[1, 3, 4, 5, 6, 7, 8, 9]


Arr 1 Dim : 2
Arr 2 Dim : 1


array([1, 3, 4, 5, 6, 7, 8, 9])